import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder OrdinalAnalysis.Compat OrdinalAnalysis.Compat.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `all` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_all
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {φ : Semiproposition (LIinfN n) 1}
    (f : ℕ → ThetaWNoteD)
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : (∀¹ φ) ∈ Γ)
    (p4 : (∀ m, f m < α))
    (p5 : (∀ m, IDnDerivable A r H (f m) (φ/[numI m] :: Γ)))
    (ih5 : ∀ m, ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → (f m) < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r (f m)) (φ/[numI m] :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hφ : ThetaWNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hfΩ : ∀ m, f m < ThetaWNoteD.Omega lv := fun m => lt_trans (p4 m) hαΩ
  have hf' : ∀ m, ThetaWNoteD.phiN lv r (f m) < ThetaWNoteD.phiN lv r α :=
    fun m => ThetaWNoteD.phiN_lt_phiN_right hr (hfΩ m) hαΩ (p4 m)
  exact .all (fun m => ThetaWNoteD.phiN lv r (f m)) hφ p2 p3 hf'
    (fun m => ih5 m hH hP hrH (hfΩ m))
