import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder OrdinalAnalysis.Compat OrdinalAnalysis.Compat.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `exs` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_exs
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {φ : Semiproposition (LIinfN n) 1}
    (m : ℕ)
    {α₀ : ThetaWNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : (∃¹ φ) ∈ Γ)
    (p4 : ThetaWNoteD.ofNat m < α)
    (p5 : α₀ < α)
    (p6 : IDnDerivable A r H α₀ (φ/[numI m] :: Γ))
    (ih6 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₀) (φ/[numI m] :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaWNoteD.Omega lv := lt_trans p5 hαΩ
  have hφ : ThetaWNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hn : ThetaWNoteD.ofNat m < ThetaWNoteD.phiN lv r α :=
    lt_trans p4 (ThetaWNoteD.lt_phiN_self hr hαΩ)
  have h0 : ThetaWNoteD.phiN lv r α₀ < ThetaWNoteD.phiN lv r α :=
    ThetaWNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p5
  exact .exs m hφ p2 p3 hn h0 (ih6 hH hP hrH hα₀Ω)
