import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder OrdinalAnalysis.Compat OrdinalAnalysis.Compat.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `and` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_and
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {φ ψ : Proposition (LIinfN n)}
    {α₀ α₁ : ThetaWNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : φ ⋏ ψ ∈ Γ)
    (p4 : α₀ < α)
    (p5 : α₁ < α)
    (p6 : IDnDerivable A r H α₀ (φ :: Γ))
    (p7 : IDnDerivable A r H α₁ (ψ :: Γ))
    (ih6 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₀) (φ :: Γ))
    (ih7 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₁ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₁) (ψ :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaWNoteD.Omega lv := lt_trans p4 hαΩ
  have hα₁Ω : α₁ < ThetaWNoteD.Omega lv := lt_trans p5 hαΩ
  exact .and (hP ∅ r α hr hαΩ hrH p1) p2 p3
    (ThetaWNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p4)
    (ThetaWNoteD.phiN_lt_phiN_right hr hα₁Ω hαΩ p5)
    (ih6 hH hP hrH hα₀Ω) (ih7 hH hP hrH hα₁Ω)
