import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `cut` of `predCut_aux` (generated by case_skeleton.py; statement generated, dispatch=induction; proved). -/
theorem predCut_aux_case_cut
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {ψ : Proposition (LIinfN n)}
    {α₀ : ThetaWNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : rk ψ < r)
    (p4 : α₀ < α)
    (p5 : IDnDerivable A r H α₀ (ψ :: Γ))
    (p6 : IDnDerivable A r H α₀ (∼ψ :: Γ))
    (ih5 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₀) (ψ :: Γ))
    (ih6 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₀) (∼ψ :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaWNoteD.Omega lv := lt_trans p4 hαΩ
  have e0 := ih5 hH hP hrH hα₀Ω
  have e1 := ih6 hH hP hrH hα₀Ω
  have hφ : ThetaWNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hφ₀ : ThetaWNoteD.phiN lv r α₀ ∈ H ∅ := hP ∅ r α₀ hr hα₀Ω hrH p5.height_mem
  have hφlt : ThetaWNoteD.phiN lv r α₀ < ThetaWNoteD.phiN lv r α :=
    ThetaWNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p4
  rcases lt_or_ge (rk ψ) μ with hlt | hge
  · -- `rk ψ ≺ μ`: the cut stays.
    exact .cut hφ p2 hlt hφlt e0 e1
  · -- `μ ⪯ rk ψ ≺ r`: cut at rank `rk ψ + 1`, Exercise 7.1 (c) down to `rk ψ`, then the outer
    -- induction hypothesis at `rk ψ ≺ r`; `φ(rk ψ, ω^{φ(r,α₀)+1}) ≺ φ(r, α)` by (φ.4).
    have hcΩ : rk ψ < ThetaWNoteD.Omega lv := lt_trans p3 hr
    have hcH : rk ψ ∈ H ∅ := hH.rk_mem (fun s hs => p5.params_head_subset ⟨s, hs, rfl⟩)
    have hprin := ThetaWNoteD.isPrin_phiN (k := lv) hr hαΩ
    have hδH : ThetaWNoteD.succ (ThetaWNoteD.phiN lv r α₀) ∈ H ∅ := hH.succ_mem hφ₀
    have hδlt : ThetaWNoteD.succ (ThetaWNoteD.phiN lv r α₀) < ThetaWNoteD.phiN lv r α :=
      ThetaWNoteD.succ_lt_prin hprin hφlt
    have hc1 : rk ψ < rk ψ + ThetaWNoteD.one := by
      rw [ThetaWNoteD.add_one_eq_succ]; exact ThetaWNoteD.lt_succ _
    have hμc1 : μ ≤ rk ψ + ThetaWNoteD.one := le_trans hge (le_of_lt hc1)
    have D : IDnDerivable A (rk ψ + ThetaWNoteD.one) H
        (ThetaWNoteD.succ (ThetaWNoteD.phiN lv r α₀)) Γ :=
      .cut hδH p2 hc1 (ThetaWNoteD.lt_succ _) (e0.mono_rank hμc1) (e1.mono_rank hμc1)
    have E := IDnDerivable.elimination hH hAb (hμ (rk ψ) hge hcΩ) D
    have hωlt : ThetaWNoteD.omegaPow (ThetaWNoteD.succ (ThetaWNoteD.phiN lv r α₀)) <
        ThetaWNoteD.phiN lv r α :=
      ThetaWNoteD.omegaPow_lt_prin hprin hδlt
    have hωΩ : ThetaWNoteD.omegaPow (ThetaWNoteD.succ (ThetaWNoteD.phiN lv r α₀)) <
        ThetaWNoteD.Omega lv :=
      lt_trans hωlt (ThetaWNoteD.phiN_lt_Omega _ _ _)
    have F := ihr (rk ψ) p3 E hH hP hcH hωΩ
    exact F.mono_height (le_of_lt (ThetaWNoteD.phiN_lt_phiN_left hcΩ hr hωΩ hαΩ p3 hωlt)) hφ
