import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `orL` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_orL
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {φ ψ : Proposition (LIinfN n)}
    {α₀ : ThetaWNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : φ ⋎ ψ ∈ Γ)
    (p4 : α₀ < α)
    (p5 : IDnDerivable A r H α₀ (φ :: Γ))
    (ih5 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₀) (φ :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaWNoteD.Omega lv := lt_trans p4 hαΩ
  have hφ : ThetaWNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have h0 : ThetaWNoteD.phiN lv r α₀ < ThetaWNoteD.phiN lv r α :=
    ThetaWNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p4
  exact .orL hφ p2 p3 h0 (ih5 hH hP hrH hα₀Ω)
