import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder OrdinalAnalysis.Compat OrdinalAnalysis.Compat.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `stage` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_stage
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {k : Fin n}
    {a : StageAt k.val}
    {t : SyntacticTerm (LIinfN n)}
    (g : StageAt k.val)
    {α₀ : ThetaWNoteD}
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : stageAt (⟨k, a⟩ : Stage n) t ∈ Γ)
    (p4 : g.1 < a.1)
    (p5 : g.1 < α)
    (p6 : g.1 ∈ H ∅)
    (p7 : α₀ < α)
    (p8 : IDnDerivable A r H α₀ (unfold (A k) k g t :: Γ))
    (ih8 : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α₀ < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α₀) (unfold (A k) k g t :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hα₀Ω : α₀ < ThetaWNoteD.Omega lv := lt_trans p7 hαΩ
  have hφ : ThetaWNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  have hglt : g.1 < ThetaWNoteD.phiN lv r α :=
    lt_trans p5 (ThetaWNoteD.lt_phiN_self hr hαΩ)
  have hα₀lt : ThetaWNoteD.phiN lv r α₀ < ThetaWNoteD.phiN lv r α :=
    ThetaWNoteD.phiN_lt_phiN_right hr hα₀Ω hαΩ p7
  exact .stage g hφ p2 p3 p4 hglt p6 hα₀lt (ih8 hH hP hrH hα₀Ω)
