import OrdinalAnalysis.Compat
import OrdinalAnalysis.IDn.PredCutAux

set_option autoImplicit false

namespace OrdinalAnalysis
namespace IDn

open FFL FFL.FirstOrder
-- case_skeleton: generated header ends here

/-- Case `nstage` of `predCut_aux` (generated by case_skeleton.py; statement only, dispatch=induction). -/
theorem predCut_aux_case_nstage
    {n : ℕ}
    {A : Fin n → Semisentence (LXIn n) 1}
    (hAb : FamilyLevelBounded A)
    {lv : ℕ}
    {μ r : ThetaWNoteD}
    (hμ : ∀ c : ThetaWNoteD, μ ≤ c → c < ThetaWNoteD.Omega lv →
      ∀ j : Fin n, c ≠ ThetaWNoteD.Omega j.val)
    (hr : r < ThetaWNoteD.Omega lv)
    (ihr : ∀ c : ThetaWNoteD, c < r → PredCutClaim A lv μ c)
    {H : Set ThetaWNoteD → Set ThetaWNoteD}
    {α : ThetaWNoteD}
    {Γ : Sequent (LIinfN n)}
    {k : Fin n}
    {a : StageAt k.val}
    {t : SyntacticTerm (LIinfN n)}
    (f : StageAt k.val → ThetaWNoteD)
    (p1 : α ∈ H ∅)
    (p2 : paramsVal Γ ⊆ H ∅)
    (p3 : nstageAt (⟨k, a⟩ : Stage n) t ∈ Γ)
    (p4 : (∀ g : StageAt k.val, g.1 < a.1 → f g < α))
    (p5 : (∀ g : StageAt k.val, g.1 < a.1 →
        IDnDerivable A r (ThetaWNoteD.adjoin H {g.1}) (f g) (∼(unfold (A k) k g t) :: Γ)))
    (ih5 : ∀ g : StageAt k.val, g.1 < a.1 → ThetaWNoteD.NiceS (ThetaWNoteD.adjoin H {g.1}) → ThetaWNoteD.PhiClosed lv (ThetaWNoteD.adjoin H {g.1}) → r ∈ (ThetaWNoteD.adjoin H {g.1}) ∅ → (f g) < ThetaWNoteD.Omega lv →
      IDnDerivable A μ (ThetaWNoteD.adjoin H {g.1}) (ThetaWNoteD.phiN lv r (f g)) (∼(unfold (A k) k g t) :: Γ))
    : ThetaWNoteD.NiceS H → ThetaWNoteD.PhiClosed lv H → r ∈ H ∅ → α < ThetaWNoteD.Omega lv →
      IDnDerivable A μ H (ThetaWNoteD.phiN lv r α) Γ := by
  intro hH hP hrH hαΩ
  have hφ : ThetaWNoteD.phiN lv r α ∈ H ∅ := hP ∅ r α hr hαΩ hrH p1
  refine .nstage (fun g => ThetaWNoteD.phiN lv r (f g)) hφ p2 p3 ?_ ?_
  · intro g hg
    have hfgΩ : f g < ThetaWNoteD.Omega lv := lt_trans (p4 g hg) hαΩ
    exact ThetaWNoteD.phiN_lt_phiN_right hr hfgΩ hαΩ (p4 g hg)
  · intro g hg
    have hfgΩ : f g < ThetaWNoteD.Omega lv := lt_trans (p4 g hg) hαΩ
    have hrH' : r ∈ (ThetaWNoteD.adjoin H ({g.1} : Set ThetaWNoteD)) ∅ := by
      rw [ThetaWNoteD.adjoin_apply]
      exact hH.1.mono (Set.empty_subset _) hrH
    exact ih5 g hg (hH.adjoin _) (hP.adjoin _) hrH' hfgΩ
